name: Daily MLB Model Predictions

on:
  schedule:
    - cron: "0 13 * * *"  # Runs daily at 8:00 AM US Central
  workflow_dispatch:      # Allows manual runs from GitHub UI

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run make_predictions.py
      run: python make_predictions.py

    - name: Commit and push predictions
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions Bot"
        git add .
        git commit -m "🤖 Auto-update: daily model predictions [skip ci]" || echo "No changes to commit"
        git push
